### ISSUE TITLE
在win10上复现代码

### ISSUE THREAD

**Issue by ennheng** [cfzd/Ultra-Fast-Lane-Detection-v2#102]
你好！想请教一下代码复现的问题，因为nvidia-dali不支持windows，所以是没有办法在windows上复现代码吗？使用预训练模型是可以生成demo的，但是无法继续训练。期待得到楼主的回答:)

**Comment by cfzd** [comment]
@ennheng 
很抱歉，这个是dali的问题，如果你想复现的话可能需要写一个纯pytorch的dataloader了

**Comment by frozenbird07** [comment]
> @ennheng 很抱歉，这个是dali的问题，如果你想复现的话可能需要写一个纯pytorch的dataloader了

请问要怎么改写这部分，目前跑了v1版本的想试下v2的改进
