### ISSUE TITLE
论文和代码不一致

### ISSUE THREAD

**Issue by zx-byte** [cfzd/Ultra-Fast-Lane-Detection-v2#104]
你好，请问在论文中resnet18的num_row和num_col不是分别为18和40吗？怎么代码里是72和81呢？这样就和resnet34一样了啊，有点不理解

**Comment by cfzd** [comment]
@zx-byte 
抱歉，这个可能是整理代码时搞错了，当初也有人提过这个问题，想着有时间再训个这个参数的模型传上来，但一直没时间做，或许你可以自己试试这个参数呢？

**Comment by zx-byte** [comment]
好的好的
