### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by lalumayang** [cfzd/Ultra-Fast-Lane-Detection-v2#117]
是否做資料擴增對於TuSimple測試資料集準確度會有差異嗎?

**Comment by cfzd** [comment]
@lalumayang 
抱歉，我不太明白你说的“資料擴增”是什么，是指数据增强吗？

**Comment by lalumayang** [comment]
就是Data Augmentation，抱歉沒說清楚。

**Comment by cfzd** [comment]
@lalumayang 
抱歉，这个我还没有试过，但是目前是做了data augmentation的，可以在这个地方看到：
https://github.com/cfzd/Ultra-Fast-Lane-Detection-v2/blob/c903880678454dfd9b55a63022368db05c00bc6d/data/dali_data.py#L152-L160
