### ISSUE TITLE
运行sh build.sh未报错也未出现run

### ISSUE THREAD

**Issue by perfectdaisy** [cfzd/Ultra-Fast-Lane-Detection-v2#141]
![3cfc2856748bc9585738b1f67c6bb93](https://github.com/cfzd/Ultra-Fast-Lane-Detection-v2/assets/67752376/6c875174-3c8e-46af-9131-c451ef9dd4fb)
在开始训练前已经执行过sh build.sh，一直只有下面这一句话显示，不知道这样显示是否正确，执行后未产生run，不知道是哪里出现问题。
原本用的python3.8，后面改成python3.7，存在同样问题。使用pytorch2.0.1，cuda11.6，gcc7.5.0

**Comment by pocky111** [comment]
请问你解决了吗

**Comment by geiyiren** [comment]
You Can't use the cuda-runtime version; you need to install the cuda-dev version of Cuda so you can use only NVCC
