### ISSUE TITLE
Tusimple数据集问题

### ISSUE THREAD

**Issue by Yysheepsheep** [cfzd/Ultra-Fast-Lane-Detection-v2#166]
你好 我想问一下在这里你有用到tusimple的验证集嘛 是怎么划分的呢

**Comment by oyoanan** [comment]
> 你好 我想问一下在这里你有用到tusimple的验证集嘛 是怎么划分的呢

你好，我也想问这个问题，你知道了吗？如果知道可以告诉我吗，非常感谢！
