### ISSUE TITLE
v1与v2版本判断车道线点不存在的逻辑不同，why？

### ISSUE THREAD

**Issue by 578223592** [cfzd/Ultra-Fast-Lane-Detection-v2#19]
如题，v1版本中是划分为num_grid来判断某个点是否存在，而在v2版本中是额外添加了一个车道线点是否存在的分支。请问改进的动机是因为对比之后效果更好吗？还是只是结构上的改进

**Comment by cfzd** [comment]
@578223592 
不精确地说，他们是等价的。但是独立出来一个存在分支可以将定位与存在这两件事给解耦，逻辑上更自洽。还有就是独立出来可以slightly增加性能。

**Comment by 578223592** [comment]
谢谢您的回复
