### ISSUE TITLE
The precision of the curvelanes

### ISSUE THREAD

**Issue by huanFigure** [cfzd/Ultra-Fast-Lane-Detection-v2#23]
Hello,
I have run your code successfully. In your paper ,the precision of resnet34 is 81.34. I didn't change your parameters in config, but I only got the precision about 71 and the epoch is 50 , can you give your parameters or your result ?

**Comment by cfzd** [comment]
@huanFigure 
The provided configs strictly correspond to the provided models. Are you using 8 GPUs with each GPU having 4 images per batch? The total batch size should be 32, and the learning rate is 0.025. If you use fewer GPUs like 4 GPUs, the learning rate should be 0.025/2.

**Comment by huanFigure** [comment]
thanks for your reply, I'll try

**Comment by huanFigure** [comment]
Hello,
My research is about knowledge distillation,can you upload your result model resnet-34 or resnet-18 on baidu drive or google drive?
