### ISSUE TITLE
Custom Video Inference

### ISSUE THREAD

**Issue by AliiiA** [cfzd/Ultra-Fast-Lane-Detection-v2#25]
Hi, I'm on the verge of publishing my own paper and to provide a comparative study, I wanted to use your algorithm as an alternative method. In doing so, I need to get a custom video inference from your network but I'm struggling to obtain an accurate result. I used the file  "Demo.py" with some changes from the last version of v.2 of this network but it wasn't helpful. I would highly appreciate it if you could share your visualization code.

Thank you very much for your help in advance.

Best,
Ali

**Comment by AliiiA** [comment]
@cfzd

**Comment by cfzd** [comment]
@AliiiA 
I'll try to upload a visualization code today.

**Comment by AliiiA** [comment]
@cfzd 
I really appreciate your efforts.

**Comment by cfzd** [comment]
@AliiiA 
I have add the visualization code. You can see it in the `Visualization` part of README.

**Comment by AliiiA** [comment]
@cfzd
I'm so grateful. Thank you
