### ISSUE TITLE
训练loss与top

### ISSUE THREAD

**Issue by zhenghao222** [cfzd/Ultra-Fast-Lane-Detection-v2#37]
请问在训练tusimple或自定义数据集中，loss下降到多少，top3达到多少合适呢？
train.py中不使用res = eval_lane(net, cfg, ep = epoch, logger = logger)可以吗？

**Comment by cfzd** [comment]
@zhenghao222 
抱歉回复较晚，loss值不绝对，只要符合正常的下降趋势即可。top3取决于每个anchor上的分类数目，如果分类数目少，那么top3自然较高，还是要看最终的评估指标，top3只是一个在训练时同setting下比较的指标。

完全可以不eval。
