### ISSUE TITLE
my_interp存在必要性的问题

### ISSUE THREAD

**Issue by linghai06** [cfzd/Ultra-Fast-Lane-Detection-v2#53]
嗨，测了一下你的工作感觉效果很棒！但是有个疑问，就是my_interp的cuda实现是有必要的吗？不知道有没有pytorch/python的版本？有的话与cuda版本相差多远？

**Comment by k8280627** [comment]
Hi, thank you very much for your work! I'm also very curious about this topic. Would it be possible to implement the functions in my_interp in Pytorch/Python?

**Comment by cfzd** [comment]
@linghai06 @k8280627 
my_interp主要是用来插值车道线坐标的，插值当然可以用pytorch或者python实现，但是实际工程中用python和pytorch实现会显著地慢（可能慢的速度远超你的想象），所以cuda只是加速了这个。这个就像卷积一样，也可以用python或pytorch实现卷积，但是这种情况下训练就会变得不现实。

my_interp is used to interpolate between lane points. Of course, you can use python or PyTorch to implement it, but it would be significantly slow (far slower than you might think). The Cuda implementation simply accelerates the speed. This is like the convolution, which you can also implement with python or PyTorch. But with such implementation, the training is impossible.

**Comment by k8280627** [comment]
I see! Thank you very much for your answer. I'm also wondering, is it possible to use CUDA 11.4 for my_interp? Would you think there's going to be any incompatibility issue? 

Thank you very much again!

**Comment by cfzd** [comment]
@k8280627 
It's a very simple CUDA program, and any CUDA version should be ok to run it.

**Comment by k8280627** [comment]
Understood. Thank you for the quick reply!

**Comment by linghai06** [comment]
> 

谢谢你详细的解答！👍🏻
