### ISSUE TITLE
训练的时候，evaluation速度过慢

### ISSUE THREAD

**Issue by AssassinJay** [cfzd/Ultra-Fast-Lane-Detection-v2#60]
跑了两轮发现，每次inference的时候GPU占用拉满，但到evaluation阶段总是占用很低，而且算一会歇一会，导致速度很慢，实测一轮推理15分钟，一轮测试30分钟，请问如何解决？

**Comment by AssassinJay** [comment]
GPU是RTX3090

**Comment by cfzd** [comment]
@AssassinJay 
这个主要是因为CULane上的官方evaluation工具是用c++写的cpu代码，基本上没法直接解决这个问题，但是可能有两个选项：
- 把OMP线程数量涨上去 `export OMP_NUM_THREADS=8`，你可以按照你CPU的核数设的再高一点，更高我实际测试好像也没什么用，但是应该会比默认的1快不少
- 使用第三方的评估工具，https://github.com/lucastabelini/LaneATT/blob/main/utils/culane_metric.py

**Comment by AssassinJay** [comment]
@cfzd 原来是这样，感谢回复！
