### ISSUE TITLE
关于hybrid-anchor system在curvelanes数据集上的使用问题

### ISSUE THREAD

**Issue by 04633435** [cfzd/Ultra-Fast-Lane-Detection-v2#75]
哈喽，感谢您分享这么棒的工作！

关于hybrid-anchor system的使用有一点疑惑想向您请教：在CUlane和Tusimple数据集上通过指定row-anchor预测ego lane和col-anchor预测side lane的方式解决了如何将车道线分配给row-anchor和col-anchor两个系统进行预测的问题。但是对于curvelanes数据集（最多提供了10条线的标注），hybrid-anchor system是如何工作来将不同的车道线按照作者的思路分给不同的anchor system呢？

期待您的回复，谢谢！

**Comment by cfzd** [comment]
@04633435 
我们在curvelanes上直接将col和row的结果进行了ensemble，就是会同时预测row和col上的结果，再做一个类似于平均的操作。
https://github.com/cfzd/Ultra-Fast-Lane-Detection-v2/blob/7df2f1280e52c16a46fb3346868d53ec795b9159/evaluation/eval_wrapper.py#L258

**Comment by 04633435** [comment]
@cfzd 
原来是这样，那我明白了，感谢您的回覆～
