### ISSUE TITLE
有序分类loss

### ISSUE THREAD

**Issue by hjw-0909** [cfzd/Ultra-Fast-Lane-Detection-v2#76]
您好，非常荣幸能看到这么棒的工作！
我有一个理论上的问题，您文章上说的更好的利用顺序关系从而提出使用分类loss和期望loss，但是我不太理解为啥这里利用到了顺序关系，这里利用到的有序性具体是指啥呢？相比而言，v1版本的文章提到的sim loss 和 shape loss更加容易理解其目的，非常希望能够得到解答，非常感谢！

**Comment by cfzd** [comment]
@hjw-0909 
一个简单的例子：imagenet上第7类是鸡，第8类是鱼，类别之间是没有任何关系的，类别更多的只是一种认为规定的顺序。在外面的框架里，分类结果直接代表着车道线的坐标，所以会有以下不同：
- 类别是有序的，第7类在第8类左边，第9类在更右边
- 类别是连续的，存在一个第7.5类的概念，代表着第7类坐标和第8类坐标中心的坐标
但在imagenet上是不可能有第7.5类的，这两个区别就是有序性
