### ISSUE TITLE
运行sh build.sh报错

### ISSUE THREAD

**Issue by Xiangyin123** [cfzd/Ultra-Fast-Lane-Detection-v2#79]
大佬你好，今天在运行sh build.sh命令后报错，报错如下：

![1](https://user-images.githubusercontent.com/86788316/211470269-ae2fabf2-ae94-429b-98c4-3d1fa2ad9685.png)

但是我又可以找到':/usr/local/cuda-11.8/bin/nvcc'这个文件

![2](https://user-images.githubusercontent.com/86788316/211470751-a7fef592-38bf-4e83-b9de-e039787dd550.png)

大佬能帮忙看下是什么原因吗？

**Comment by cfzd** [comment]
@Xiangyin123 
你直接在命令行输入
```
nvcc -V
```
看看能不能找到，以及会输出什么

**Comment by Xiangyin123** [comment]
![3](https://user-images.githubusercontent.com/86788316/211493349-cc389eb8-3c31-4d28-a6dd-e60c2a948359.png)

**Comment by cfzd** [comment]
@Xiangyin123 
要不看一下`$PATH`的值：
```
echo $PATH
```
我注意到你的报错里面那个路径前面有个冒号，是不是这个原因造成的。如果还是对的，那你试试直接复制那个报错的路径`/usr/local/cuda-11.8/bin/nvcc`，然后执行它看看能不能执行

**Comment by Xiangyin123** [comment]
我也注意到了这个冒号
执行  echo $PATH 结果是这样的


![4](https://user-images.githubusercontent.com/86788316/211499461-cb5000e0-42b8-4678-896c-f9b49c68fd13.png)

**Comment by Xiangyin123** [comment]
是环境变量有问题吗大佬

**Comment by cfzd** [comment]
@Xiangyin123 
要不你试试把`build.sh`中注视掉的前几行取消注释，然后重新执行一遍它

**Comment by Xiangyin123** [comment]
我尝试取消注释了，重新执行依旧报相同的错误

**Comment by cfzd** [comment]
@Xiangyin123 
你要不试试执行这个再编译：
```
export CUDA_HOME=/usr/local/cuda-11.8
```
或者
```
export CUDA_HOME=/usr/local/cuda
```

**Comment by Xiangyin123** [comment]
已解决，谢谢大佬～
