### ISSUE TITLE
报错：_pickle.UnpicklingError: invalid load key, '\x18'

### ISSUE THREAD

**Issue by Xiangyin123** [cfzd/Ultra-Fast-Lane-Detection-v2#86]
嗨，大佬。我参考CULane数据集制作了自己的数据集并成功利用trian.py文件进行训练，但是用自己的模型运行demo.py测试时，发生了报错(用预训练模型culane_res34.py不会报错)。以下是更多细节截图：
1.报错截图：
![2](https://user-images.githubusercontent.com/86788316/217438650-0d6dcc65-dbce-4c45-ba7e-55c42cb075dc.png)
2.训练代码截图(我注释掉了图中两个地方)：
![1](https://user-images.githubusercontent.com/86788316/217438068-0bb78446-4562-4e8d-a5a5-ab23371fa816.png)
3.训练时的configs文件：
![3](https://user-images.githubusercontent.com/86788316/217438844-0df40e7e-df58-4950-aab6-8a4ffac245ca.png)
4.测试时的configs文件：
![4](https://user-images.githubusercontent.com/86788316/217438858-f42cbbc3-492c-4e58-8906-aa391065528e.png)

**Comment by Xiangyin123** [comment]
已解决

**Comment by Minweak** [comment]
想问问是怎么解决的，我也遇到了同样的问题

**Comment by cfzd** [comment]
@Minweak 
可以贴一下完整报错吗
