### ISSUE TITLE
本算法能否实现在已训练好的模型下接着训练？

### ISSUE THREAD

**Issue by Xiangyin123** [cfzd/Ultra-Fast-Lane-Detection-v2#87]
嗨，大佬，这个算法可以在已训练好的模型下接着训练吗？

**Comment by cfzd** [comment]
@Xiangyin123 
载入原来的权重继续训练就可以了，可以看看这部分代码：
https://github.com/cfzd/Ultra-Fast-Lane-Detection-v2/blob/849fa7b90c189b646d12adc1d807bec54e982031/train.py#L89

**Comment by Xiangyin123** [comment]
感谢大佬指定，对我帮助很大！
我还有个小小疑问，我的图片尺寸是1920*1280，和culane的1640*590还不一致。我是应该把自己的图片resize成1640*590后进行标注和训练还是修改您的源代码好一些？如果要修改您的源代码，需要修改哪些地方？

**Comment by cfzd** [comment]
@Xiangyin123 
因为我并不清楚你的数据是什么样的，所以这个问题没法帮助你。

**Comment by Xiangyin123** [comment]
![video1_2m_0000179105_sec_1666667225_nsec_821882312_1920x1280](https://user-images.githubusercontent.com/86788316/218943258-da8d2301-62a1-4668-a0bc-4a719caccb71.png)

这样的图片，尺寸为1920*1280

**Comment by 578223592** [comment]
> ![video1_2m_0000179105_sec_1666667225_nsec_821882312_1920x1280](https://user-images.githubusercontent.com/86788316/218943258-da8d2301-62a1-4668-a0bc-4a719caccb71.png)
> 
> 这样的图片，尺寸为1920*1280

两种方法应该都是可行的，为了方便起见可以直接resize图片

**Comment by FunnyWii** [comment]
> 两种方法应该都是可行的，为了方便起见可以直接resize图片

请问这里的resize是用等比例缩放，还是裁剪呢？
直接裁剪成1640*590是不是也可以
