### ISSUE TITLE
windows cant install Nvidia-DALI accelerator module

### ISSUE THREAD

**Issue by Hymilex** [cfzd/Ultra-Fast-Lane-Detection-v2#95]
![Snipaste_2023-03-07_21-34-42](https://user-images.githubusercontent.com/23647858/223437536-7580d604-89f3-4f20-ad22-c5d11fd7e020.jpg)

**Comment by Hymilex** [comment]
@cfzd i wanna run ufld-v2 on windows,but nvidia-dali seems not  installed successfully,may i have any better ways to solve it? more thanks!

**Comment by cfzd** [comment]
@Hymilex 
It's a problem of DALI. Sorry that it cannot run on Windows. You might have two ways:
- Use Linux system
- Write a PyTorch Dataloader (I think it is not very hard since the DALI is only an accelerator, just copy the logic to a PyTorch-based dataloader)

**Comment by Hymilex** [comment]
> 

Got it!Thank you very much again.

**Comment by Hymilex** [comment]
@cfzd Got it!Thank you very much again.

**Comment by Lyfun222** [comment]
@Hymilex 
Can I use WSL2 instead of Linux to run this program?
